name: flutter_test_vocacional_1
description: Este es un test vocacional hecho por Brenda Luna Luna en DGETI
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=3.3.0 <4.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    google_fonts: ^6.1.0
    carousel_slider: ^4.2.1
    card_swiper: ^3.0.1
    flutter_launcher_icons: ^0.13.1
    provider: 6.1.2
    cloud_firestore: ^4.15.10
    firebase_auth: ^4.18.0
    firebase_storage: ^11.6.11
    auto_size_text: ^3.0.0
    firebase_core: ^2.27.2
    url_strategy: ^0.2.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
flutter_launcher_icons:
    android: true
    ios: true
    image_path: assets/icon/Imagotipo_DGETI.png
flutter:
    uses-material-design: true
    assets:
        - assets/images/dgti.png
        - assets/images/rojo.png
        - assets/images/azul.png
        - assets/images/logistica.jpeg
        - assets/images/electronica.jpeg
        - assets/images/programacion.jpeg
        - assets/images/rh.jpeg
        - assets/images/robotica.jpeg
        - assets/images/puericultura.jpeg
        - assets/images/logo2.png
    fonts:
        -
            family: Nunito Black
            fonts:
                -
                    asset: assets/fonts/nunito/Nunito-Black.ttf
                -
                    asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
                    style: italic
        -
            family: Nunito
            fonts:
                -
                    asset: assets/fonts/nunito/Nunito-Medium.ttf
                    weight: 500
                -
                    asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
                    weight: 600
                    style: italic


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages